name: xalan

on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: self-hosted

    steps:

      - name: Full cleanup Docker and previous files
        run: |
          echo "Cleaning Docker..."

          sudo docker stop $(sudo docker ps -aq) || true
          sudo docker rm -f $(sudo docker ps -aq) || true

          sudo docker system prune -af --volumes || true
          sudo docker builder prune -af || true

          echo "Cleaning DaCapo folders..."

          sudo chown -R $(whoami):$(whoami) /tmp/dacapobench || true
          sudo chown -R $(whoami):$(whoami) ./dacapobench || true

          sudo rm -rf /tmp/dacapobench || true
          sudo rm -rf ./dacapobench || true

          echo "Cleanup finished"


      - name: Checkout
        uses: actions/checkout@v4


      - name: Prepare DaCapo
        run: |
          cp -r ~/Documentos/dacapobench ./dacapobench


      - name: Build Docker image
        run: |
          docker build \
            -f .github/workflows/Dockerfile \
            -t xalan-energy .


      - name: Wait before benchmark
        run: |
          echo "Waiting 30 seconds before starting measurements..."
          sleep 30


      - name: Run Xalan benchmark 30 times with measurements
        run: |
          for i in $(seq 1 30)
          do
            echo "======================================"
            echo " Starting Xalan iteration $i/30"
            echo "======================================"

            /home/carlos/runner-config/scripts/setup.sh \
              "start_measurement" \
              "baseline=true" \
              "benchmark" \
              "software" \
              "perf" \
              "interval=10" \
              "events=power/energy-pkg/,power/energy-cores/"


            docker run --rm --privileged xalan-energy \
            java -jar /home/carlos/xalan/dacapobench/benchmarks/dacapo-evaluation-git-e947cbfc-dirty/launchers/xalan.jar \
            -s large xalan


            /home/carlos/runner-config/scripts/setup.sh \
              "end_measurement" \
              "benchmark"


            echo "Finished Xalan iteration $i/30"

            sleep 30

          done
