name: Xalan DaCapo 

on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare DaCapo
        run: |
          cp -r ~/Documentos/dacapobench ./dacapobench

      - name: Build Docker
        run: |
          docker build \
            -f .github/workflows/Dockerfile \
            -t xalan-energy .

      - name: Run benchmark
        run: |
          docker run --rm --privileged xalan-energy
